In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
 
import wrds

c:\Users\YeonChan Kang\anaconda3\envs\fdb\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
db = wrds.Connection()

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [4]:
db.list_tables(library='contrib_global_factor')

['global_factor']

In [5]:
countries = pd.read_excel('https://github.com/bkelly-lab/ReplicationCrisis/raw/master/GlobalFactors/Country%20Classification.xlsx')

In [8]:
countries

   excntry msci_development         region
0      USA        developed  north america
1      ARE         emerging    middle east
2      JPN        developed           asia
3      HKG        developed           asia
4      GBR        developed         europe
..     ...              ...            ...
91     UGA        not rated         africa
92     URY        not rated            NaN
93     VEN        not rated  south america
94     ZMB        not rated         africa
95     ZWE       standalone         africa

[96 rows x 3 columns]

In [6]:
chars = pd.read_excel('https://github.com/bkelly-lab/ReplicationCrisis/raw/master/GlobalFactors/Factor%20Details.xlsx')

In [7]:
chars

,abr_hxz,name,name_new,abr_jkp,time_to_create,lagged_denom,cite,variations,group,in-sample period,t-stat,p-value,direction,significance,controls
0,Sue,Earnings surprise,Standardized earnings surprise,niq_su,NaN,NaN,Foster Olsen and Shevlin (1984),3.0,Momentum,1974 - 1981,9.11,NaN,1.0,1.0,2.0
1,Abr,Cumulative abnormal stock returns around earni...,Cumulative abnormal stock returns around earni...,NaN,3,NaN,Chan Jegadeesh and Lakonishok (1996) 1972/1,3.0,Momentum,1977 - 1993,4.25,NaN,1.0,NaN,2.0
2,Re,Revisions in analystsâ€™ earnings forecasts,Revisions in analystsâ€™ earnings forecasts,NaN,A,NaN,Chan Jegadeesh and Lakonishok (1996) 1976/7,3.0,Momentum,1977 - 1993,3.1,NaN,1.0,NaN,2.0
3,R6,"Price momentum, prior 6-month returns",Price momentum t-6 to t-1,ret_6_1,NaN,NaN,Jegadeesh and Titman (1993),3.0,Momentum,1965 - 1989,2.29,NaN,1.0,1.0,0.0
4,R11,"Price momentum, prior 11-month returns",Price momentum t-12 to t-1,ret_12_1,NaN,NaN,Jegadeesh and Titman (1993),3.0,Momentum,1965 - 1989,NaN,NaN,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,NaN,Mispricing factor: Management,Mispricing factor: Management,mispricing_mgmt,NaN,NaN,Stambaugh and Yuan (2016),NaN,NEW,1967 - 2013,NaN,NaN,1.0,1.0,NaN
251,NaN,Quality minus Junk: Composite,Quality minus Junk: Composite,qmj,NaN,NaN,"Assness, Frazzini and Pedersen (2018)",NaN,NEW,1957 - 2016,NaN,NaN,1.0,1.0,NaN
252,NaN,Quality minus Junk: Profitability,Quality minus Junk: Profitability,qmj_prof,NaN,NaN,"Assness, Frazzini and Pedersen (2018)",NaN,NEW,1957 - 2016,NaN,NaN,1.0,1.0,NaN
253,NaN,Quality minus Junk: Growth,Quality minus Junk: Growth,qmj_growth,NaN,NaN,"Assness, Frazzini and Pedersen (2018)",NaN,NEW,1957 - 2016,NaN,NaN,1.0,1.0,NaN
254,NaN,Quality minus Junk: Safety,Quality minus Junk: Safety,qmj_safety,NaN,NaN,"Assness, Frazzini and Pedersen (2018)",NaN,NEW,1957 - 2016,NaN,NaN,1.0,1.0,NaN

In [ ]:
sql_query= f"""
          SELECT id, eom, excntry, gvkey, permno, size_grp, me, ret_exc_lead1m
                   FROM contrib.global_factor
                   WHERE common=1 and exch_main=1 and primary_sec=1 and obs_main=1 and
                   excntry='DNK'
          """

In [ ]:
data = db.raw_sql(sql_query)